In [4]:
import numpy

### Step Activation Function

### Linear Activation Function

### The Sigmoid Activation Function

In [8]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


### TanH Activation Function

In [9]:
import torch

def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

### The Rectified Linear Activation Function

In [2]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs = []

for i in inputs:
    if i > 0:
        outputs.append(i)
    else:
        outputs.append(0)
        
print(outputs)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
import torch
import matplotlib.pyplot as plt

prelu = torch.nn.PReLU(num_parameters=1)
x = torch.range(-5., 5., 0.1)
y = prelu(x)

plt.plot(x.numpy(), y.numpy())
plt.show()

### Softmax Activation Function

In [3]:
layer_outputs = [4.8, 1.21, 2.385]
E = 2.71828182846

exp_values = []

for output in layer_outputs:
    exp_values.append(E ** output)
    
exp_values

[121.51041751893969, 3.3534846525504487, 10.85906266492961]

In [4]:
## Normalizing the values

norm_base = sum(exp_values)
norm_values = []

for value in exp_values:
    norm_values.append(value / norm_base)

print(norm_values)
print("Sum of normalized values: ", sum(norm_values))

[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values:  1.0


In [5]:
import numpy as np

exp_values = np.exp(layer_outputs)
exp_values

array([121.51041752,   3.35348465,  10.85906266])

In [6]:
norm_values = exp_values / np.sum(exp_values)
norm_values

array([0.89528266, 0.02470831, 0.08000903])

In [8]:
layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

In [11]:
## sum columnwise
np.sum(layer_outputs, axis=0, keepdims=True)

array([[15.11 ,  0.451,  2.611]])

In [12]:
## sum rowise
np.sum(layer_outputs, axis=1, keepdims=True)

array([[8.395],
       [7.29 ],
       [2.487]])

#### Softmax class

In [13]:
class Softmax:
    
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True)) ## large numbers can really disrupt a neural net
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [14]:
softmax = Softmax()

softmax.forward([[1, 2, 3]])
print(softmax.output)

[[0.09003057 0.24472847 0.66524096]]


In [15]:
softmax.forward([[0.5, 1, 1.5]])
print(softmax.output)

[[0.18632372 0.30719589 0.50648039]]


### Upto Here

In [16]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        
class Softmax:
    
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [17]:
X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
